### ISSUE TITLE
Release work flow for Dog-mode 

### ISSUE THREAD

**Issue by AhmedElkazzaz** [eclipse-velocitas/vehicle-app-python-sdk#136]
### Question

I have copied the dog-mode app example in my template ,but I the release work flow failed.

Here you can find my repo :
https://github.com/AhmedElkazzaz/dog-example-final.git
-------------------------------------------------
And Here is the error in [gen-desired-state / Generate desired state for dogmode]
Generating service SDK for '...tent.com/eclipse/kuksa.val.services/v0.2.0/hvac_service/proto/sdv/edge/comfort/hvac/v1/hvac.proto'
/__t/Python/3.10.14/x64/bin/python: Error while finding module specification for 'grpc_tools.protoc' (ModuleNotFoundError: No module named 'grpc_tools')
Traceback (most recent call last):
  File "/github/home/.velocitas/packages/devenv-devcontainer-setup/v2.4.4/./grpc-interface-support/src/main.py", line 140, in <module>
    main(args.verbose)
  File "/github/home/.velocitas/packages/devenv-devcontainer-setup/v2.4.4/./grpc-interface-support/src/main.py", line 133, in main
    generate_single_service(factory, if_config)
  File "/github/home/.velocitas/packages/devenv-devcontainer-setup/v2.4.4/./grpc-interface-support/src/main.py", line 96, in generate_single_service
    generator.generate_package(is_client, is_server)
  File "/github/home/.velocitas/packages/devenv-devcontainer-setup/v2.4.4/grpc-interface-support/src/python.py", line 139, in generate_package
    self.__invoke_code_generator()
  File "/github/home/.velocitas/packages/devenv-devcontainer-setup/v2.4.4/grpc-interface-support/src/python.py", line 57, in __invoke_code_generator
    subprocess.check_call(
  File "/__t/Python/3.10.14/x64/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '-m', 'grpc_tools.protoc', '-I/github/home/.velocitas/projects/3e94ee1[228](https://github.com/AhmedElkazzaz/dog-example-final/actions/runs/9869603639/job/27253663012#step:5:229)1cde6d38ee50832e74046a/services', '--python_out=/github/home/.velocitas/projects/3e94ee12281cde6d38ee50832e74046a/services/hvac', '--pyi_out=/github/home/.velocitas/projects/3e94ee12281cde6d38ee50832e74046a/services/hvac', '--grpc_python_out=/github/home/.velocitas/projects/3e94ee12281cde6d38ee50832e74046a/services/hvac', '/github/home/.velocitas/projects/3e94ee12281cde6d38ee50832e74046a/services/hvac.proto']' returned non-zero exit status 1.
    ExecExitError: Program returned exit code: 1
Error: Process completed with exit code 1.

**Comment by tuanzimplistic** [comment]
this project has very low quality. Do not know how they can use it for production. Terrible.

**Comment by dennismeister93** [comment]
Hi @AhmedElkazzaz
Thanks for reporting this issue. The DogMode example is unfortunately out of date and not correctly supported on our current state. It lives here in the examples to have a code-wise orientation on how you can realize such functionality and see how a more detailed code implementation looks like.

I recommend you to try out the standard example application mentioned on our [quickstarting guide](https://eclipse.dev/velocitas/docs/tutorials/quickstart/quickstart/) to just get started!

After you have successfully get started with that one you could either try out the seat-adjuster example for instance or even get deeper into the dog mode again and try to get it working again when you get into all our concepts. We are happy to support of getting it to work again and feel free to create any PR of fixing this example.

Kind Regards!

**Comment by dennismeister93** [comment]
> this project has very low quality. Do not know how they can use it for production. Terrible.

Hi @tuanzimplistic,

Thanks for your feedback. It's always interesting to see such strong opinions, especially from those outside the project. If you have any concrete suggestions on how to improve it, we are all ears. It's easy to criticize from the sidelines, but constructive feedback is what really helps open source projects get better. Feel free to contribute if you have the expertise.

All the best!

**Comment by AhmedElkazzaz** [comment]
Hello @dennismeister93 

Thanks for your reply ,I have alredy fixed the problem with deploying the seat adjuster ,deployed it and worked with it,
 I tried to also to deploy the dog-mode because it is the only example for working with grpc service and I am stuck in generating the image .
If dog-mode is not supported ,do you offer another example to demonstrate working with grpc  services ?

Best Regards,
Ahmed

**Comment by tuanzimplistic** [comment]
> > this project has very low quality. Do not know how they can use it for production. Terrible.
> 
> Hi @tuanzimplistic,
> 
> Thanks for your feedback. It's always interesting to see such strong opinions, especially from those outside the project. If you have any concrete suggestions on how to improve it, we are all ears. It's easy to criticize from the sidelines, but constructive feedback is what really helps open source projects get better. Feel free to contribute if you have the expertise.
> 
> All the best!

I tried 3 projects:
- try to generate vss model from cli -> error
- kuksa databroker -> error
- velocitas -> error

**Comment by MP91** [comment]
> Hello @dennismeister93
> 
> Thanks for your reply ,I have alredy fixed the problem with deploying the seat adjuster ,deployed it and worked with it, I tried to also to deploy the dog-mode because it is the only example for working with grpc service and I am stuck in generating the image . If dog-mode is not supported ,do you offer another example to demonstrate working with grpc services ?
> 
> Best Regards, Ahmed

Hey @AhmedElkazzaz 

the GRPC integration changed a lot recently and we are still fixing some issues as you can also see in https://github.com/eclipse-velocitas/devenv-devcontainer-setup/pull/75. Once everything is working as expected we will also work on the examples.

For now the only thing we have are the integration tests, but maybe that also helps you already. Please take a look [here for a server implementation](https://github.com/eclipse-velocitas/devenv-devcontainer-setup/blob/main/test/python/service_server/app/src/launcher.py) or [here for the client side](https://github.com/eclipse-velocitas/devenv-devcontainer-setup/blob/main/test/python/service_client/app/src/launcher.py).

Hope that helps, but please feel free to ask if you need anything else.

Kind regards

**Comment by MP91** [comment]
> > > this project has very low quality. Do not know how they can use it for production. Terrible.
> > 
> > 
> > Hi @tuanzimplistic,
> > Thanks for your feedback. It's always interesting to see such strong opinions, especially from those outside the project. If you have any concrete suggestions on how to improve it, we are all ears. It's easy to criticize from the sidelines, but constructive feedback is what really helps open source projects get better. Feel free to contribute if you have the expertise.
> > All the best!
> 
> I tried 3 projects:
> 
>     * try to generate vss model from cli -> error
> 
>     * kuksa databroker -> error
> 
>     * velocitas -> error

Hello @tuanzimplistic, 
as @dennismeister93 also already mentioned: with such comments we can't really improve our product. So please feel free to open an issue in the respective repositories and provide as much details as possible.

For now I would recommend that you start reading the [quickstart guide](https://eclipse.dev/velocitas/docs/tutorials/quickstart/quickstart/) and try to understand first how our product should be used.

Most of the repositories are not meant to be used standalone, but are bundled together in the template repositories which you can use to develop your vehicle apps.

Furthermore the databroker is not even part of this project, it belongs to the KUKSA project. But again if you have any details of the error you encountered feel free to open an issue on the repository and help the product to get better.

Thanks!
